### ISSUE TITLE
Find a solution to visualize 60000 trees

### ISSUE THREAD

**Issue by RalucaNicola** [CaptainInler/findAtree#10]
One approach would be to use geofire to only get the trees that are around the center of the map: https://github.com/CaptainInler/geofire.

This ticket is also about changing the symbology for the map and the trees.

**Comment by RalucaNicola** [comment]
solution: We select trees in a smaller region and load only a few thousand.

**Comment by RalucaNicola** [comment]
try it again using Beta feature layer editing

**Comment by CaptainInler** [comment]
@RalucaNicola Es ist nicht unbeding nötig, dass alle Bäume drin sind. Es ist auch ok, wenn nur einen Teil der Bäume in der Karte sind, also so wie es jetzt ist.

**Comment by RalucaNicola** [comment]
implementiert mit WebGL FeatureLayer, es ist alles im master.
