### ISSUE TITLE
Create basic test cases

### ISSUE THREAD

**Issue by beatfleischli** [CaptainInler/findAtree#17]
- setup first tests
- which tests might make sense? might be useful?

**Comment by beatfleischli** [comment]
Zwischenstand vom 8. März 2018:
Auf branch beat/unitTest sieht es mittlerweile so aus:
![screen shot 2018-03-10 at 10 01 58](https://user-images.githubusercontent.com/31900561/37240328-236faede-244a-11e8-8dd5-e7a29b915ebf.png)
Alle früheren Fehlermeldungen sind weg, aber die esri-module werden nicht gefunden.

**Comment by CaptainInler** [comment]
testausführen funktioniert jetzt ohne diese Fehler

**Comment by CaptainInler** [comment]
Nach Silvan sollten wir ein paar test's für die services schreiben:
@beatfleischli: Bitte einen Unittest für auth.service schreiben
@RalucaNicola: Bitte einen Unittest für map-data schreiben
@captaininler: Bitte einen Unittest für guess-panle (zählen der Punkte) schreiben

**Comment by RalucaNicola** [comment]
Ich habe ein Test für map data service hinzugefügt: https://github.com/CaptainInler/findAtree/pull/41/commits/ff1f00c1b347be6dca148e7ba946841cf04020e4

und ich will noch einen für App component falls ich das hinkriege: https://github.com/CaptainInler/findAtree/pull/41/commits/72927eebc4eac4d2a60d6b60a9b0fab0f39223df

**Comment by CaptainInler** [comment]
Habe auch zwei Unittest erstellt. Allerdings sind die etwas unnötig, das sie das testen was eingegeben wird..
zwei andere tests funktionieren nicht. ich erhalte immer fehlermeldungen zu "AngularFireAuth" obwohl das mit dem test eigentlich nichts zu tun hat.. https://github.com/CaptainInler/findAtree/commit/3d40a60da381ecb933afea9ea0604d64dca6ad68

**Comment by RalucaNicola** [comment]
Darf ich das mergen? https://github.com/CaptainInler/findAtree/pull/41https://github.com/CaptainInler/findAtree/pull/41 

1 test-suite ist für den EditPanel und 1 test-suite ist für mapDataService. Jeder enthält mehrere test cases.

@CaptainInler oh ich glaube man müsste alle die Services mocken...ich musste auch das AppState service mocken, ich habe meine MockState hier erstellt: https://github.com/CaptainInler/findAtree/pull/41/commits/83c6f46cc3ba94897b67bcffbc70d6a9889434e1#diff-2be6563b1198db3a97cd0aeeaa6df4c9. Bei MapDataService war ich zu faul und habe direkt den Service benutzt weil es keine Fehler im Test gegeben hat.

**Comment by beatfleischli** [comment]
Ich glaube, wir haben genügend Tests beisammen. Ich werde deshalb diesen Issue schliessen.
