### ISSUE TITLE
current tree, current location

### ISSUE THREAD

**Issue by beatfleischli** [CaptainInler/findAtree#34]
Selected tree should be highlighted.
Would be nice to see current user position on the map, if using a mobile.

**Comment by CaptainInler** [comment]
> Selected tree should be highlighted.

Definitv wichtig. weisst du wie man das machen könnte oder ist das was für @RalucaNicola ?


> Would be nice to see current user position on the map, if using a mobile.

Ich denke nicht, dass es viel sinn macht das zu implementieren. Wir sollten uns besser auf die bestehenden probleme konzentrieren..

**Comment by beatfleischli** [comment]
Ich glaube, das ist was, was Raluca machen muss. Auch die Position anzeigen.

Gruss
Beat

**Comment by RalucaNicola** [comment]
ja, highlighting mache ich. 

Position anzeigen schaue ich noch, falls es noch Zeit dafür bleibt. Das kann man im Mobile und Desktop machen.

**Comment by RalucaNicola** [comment]
gemacht, es ist in Branch https://github.com/CaptainInler/findAtree/tree/raluca/geolocator.

**Comment by CaptainInler** [comment]
wäre noch cool, wenn man das mit dem smartphone testen könnte. aber das geht, glaube ich, nur wenn man den branch in den master merged damit man via githubpage darauf zugreifen kann.. oder kenn jemand einen anderen weg?
