### ISSUE TITLE
Set up user accounts

### ISSUE THREAD

**Issue by RalucaNicola** [CaptainInler/findAtree#7]
This ticket is about setting up a database with users and creating the authentication component. Front end can also be designed using a login page (see mockup).

@beatfleischli please add or delete info in this ticket as you see best. I can swap with you if you get bored of it and want to do more front end.

**Comment by beatfleischli** [comment]
I didn't add a new db yet but am using the one available with firebase authentication. It's possible to add display name for new accounts there. If we like to store more user information we probably will have to add a user db later.
